baseURL = 'http://test.brain-hole.org'  # 网站的基本URL
languageCode = 'zh'  # 网站使用的语言代码，这里是中文
title = 'BrainSpace'  # 网站标题
theme = 'BrainSpace'  # 使用的主题名称
pagination.pagerSize = 12  # 分页的大小，每页显示的项目数量
disableKinds = ["taxonomy", "section"]  # 禁用分类和部分功能

[params]
  description = '欢迎来到 BrainSpace，一个探索并记录灵感，记录想法与故事的个人空间！'  # 网站描述
  
  imgurl = "https://bu.dusays.com"  # 图片资源URL
  
  byYear = '2023'  # 版权起始年份
  Time = '2022-12-28T00:00:00'  # 网站创建时间
  Miit = 'MIIT20230001号'  # 备案号
  Miiturl = 'https://beian.miit.cn.com'  # 备案查询URL
  
  appId = 'Httu4wmKvScZU17RhjItXFCj-gzGzoHsz'  # LeanCloud应用ID
  appKey = 'Sp70fLdE96aOASJCNgZ9ZUCJ'  # LeanCloud应用密钥
  serverURL = 'https://httu4wmk.lc-cn-n1-shared.com'  # LeanCloud服务器URL
  
  twitter = 'YOUR_TWITTER_ID'  # 
  
  avatar = '/2023/11/07/6549e08158c74.webp'  # 头像图片路径
  topavatar = '/2023/12/29/658e16beb2c7b.webp'  # 顶部头像图片路径
  Brainhole = '/2024/06/11/6668356c432ea.webp'  # 灵感图片路径
  classmate = '/2024/09/29/66f95c66cad27.webp'  # 同学图片路径
  name = 'Brain hole'  # 网站名称
  
  aboutme = '门前的花自杀了，一生不愁吃穿，唯独缺自由与爱。'  # 关于我的简介
  githuburl = 'https://github.com/mrxie68'  # GitHub链接
  twitterurl = '/class/gallery/'  # 推特链接
  searchurl = '/class/gallery/'  # 搜索页面链接
  aboutmeurl = '/class/about/'  # 关于我页面链接
  

  math = true  # 启用数学公式渲染
  


# 黑白页面设置
customCSSStartDate = "2024-10-26"  # 开始日期
customCSSEndDate = "2024-10-28"  # 结束日期


[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true  # 允许不安全的HTML渲染

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10  # 排序权重

  [[menu.main]]
    identifier = "gallery"
    name = "回忆"
    url = "/class/gallery/"
    weight = 20  # 排序权重

  [[menu.main]]
    identifier = "message"
    name = "留言"
    url = "/class/message/"
    weight = 45  # 排序权重

  [[menu.main]]
    identifier = "link"
    name = "友链"
    url = "/class/Link/"
    weight = 40  # 排序权重

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/class/about/"
    weight = 50  # 排序权重

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true  # 输出压缩后的内容
